version: '2'
services:
  cloud-admin:
    image: cloud/cloud-admin
    ports:
      - "9777:9777"
    links:
      - sentinel
      - redis
      - nacos
      - mysql
    environment:
      - NACOS_HOST=nacos
      - NACOS_PORT=8848
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - SENTINEL_HOST=sentinel
      - SENTINEL_PORT=8080
  cloud-monitor:
      image: cloud/cloud-monitor
      ports:
        - "9999:9999"
      links:
        - nacos
      environment:
        - NACOS_HOST=nacos
        - NACOS_PORT=8848
  cloud-gate:
    image: cloud/cloud-gate
    ports:
      - "8765:8765"
    links:
      - cloud-admin
      - sentinel
      - redis
      - nacos
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
    environment:
      - NACOS_HOST=nacos
      - NACOS_PORT=8848
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENTINEL_HOST=sentinel
      - SENTINEL_PORT=8080
      - AUTH_SERVER_HOST=cloud-admin
      - AUTH_SERVER_PORT=9777
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/redis:/var/lib/redis
  sentinel:
    image: anjia0532/sentinel-docker
    ports:
      - "8080:8080"
  cloud-ui:
    image: cloud/cloud-ui
    ports:
      - "80:80"
    links:
      - cloud-gate
  nacos:
    image: nacos/nacos-server
    ports:
      - "8848:8848"
    links:
      - mysql
    volumes:
      - ./standalone-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    environment:
      - MYSQL_MASTER_SERVICE_HOST=mysql
      - MYSQL_MASTER_SERVICE_DB_NAME=cloud_nacos
      - MYSQL_MASTER_SERVICE_PORT=3306
      - MYSQL_MASTER_SERVICE_USER=root
      - MYSQL_MASTER_SERVICE_PASSWORD=123456
      - MODE=standalone
  mysql:
    environment:
       - MYSQL_ROOT_PASSWORD=123456
       - MYSQL_USER=test
       - MYSQL_PASS=123456
    image: docker.io/mysql:5.7
    volumes:
        - ./db:/var/lib/mysql
        - ./conf/my.cnf:/etc/my.cnf"
        - ./init:/docker-entrypoint-initdb.d/
    ports:
        - "3306:3306"
